/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2008-12-14, 01:23:57
 */

package gui.main;

import gui.main.contact_partial.ContactPartialPanel;
import javax.swing.tree.TreeCellRenderer;

/**
 *
 * @author comboy
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        //contacts_tree.addTreeSelectionListener(new MyTreeSelectionListener())
        //TreeCellRenderer renderer = new ContactPartial();
        //contacts_tree.setCellRenderer(renderer);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    combo_box_presence = new javax.swing.JComboBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    contacts_tree = new javax.swing.JTree();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    menu_add_contact = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("EBIM - Even Better Instant Messanger");

    jToolBar1.setRollover(true);

    combo_box_presence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Taka <b>sobie</b> sraka", "Item 2", "Item 3", "Item 4" }));

    contacts_tree.setRootVisible(false);
    jScrollPane1.setViewportView(contacts_tree);

    jMenu1.setText("File");

    menu_add_contact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
    menu_add_contact.setText("Dodaj kontakt...");
    menu_add_contact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menu_add_contactActionPerformed(evt);
      }
    });
    jMenu1.add(menu_add_contact);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
      .addComponent(combo_box_presence, javax.swing.GroupLayout.Alignment.TRAILING, 0, 189, Short.MAX_VALUE)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(combo_box_presence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void menu_add_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_contactActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_menu_add_contactActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public javax.swing.JTree jebaneDrzewko() {
        return contacts_tree;
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox combo_box_presence;
  private javax.swing.JTree contacts_tree;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JMenuItem menu_add_contact;
  // End of variables declaration//GEN-END:variables

}
